### ISSUE TITLE
Math Duel Game!

### ISSUE THREAD

**Issue by JohnRyanAudio** [JohnRyanAudio/w0rmh0le#7]
# Overview

A user can challenge another user to a math duel. The challenged user can choose to accept or reject the challenge. Once the challenge has been accepted, w0rmb0t would give a countdown and then post a math problem in the chat.
Each user gives their answer as fast as possible, and can only give one answer. A correct answer is a 'hit' and a wrong answer is a 'miss'. If a user gets 'hit' before they give their answer, even if it is correct, then their answer is automatically a 'miss'.
I imagine each user would have like 5 hp or something like that, so the first user to deplete the other user's hp is the winner.

## Possible Features

- Equipment System
  - Ideas:
    - Better guns maybe have a chance to hit for two damage
    - Body armor to take more hits
    - Lucky rabbit's foot gives another chance at a missed problem
- Experience System
  - This would have to be mostly cosmetic in order to avoid unbalanced games. However, equipment could be awarded like every 5 levels or so, which I don't think would be too unbalanced. A really good lvl 1 duelist could still beat a higher level duelist. I mean, we need progression, right?!
- Abilities System
  - Abilities would be used in place of an answer, and would be expended on use.
  - Ideas:
    - 'Roll' - expend once per duel to avoid a 'hit' instead
    - 'Kick Sand' - opponent loses next turn
    - 'Called Shot' - If your next answer 'hit's do 3 damage.
- Avatars
  - Give your duelist a face!

## Requirements

- The base game has no additional requirements.
- Pretty much all additional features outside of the base game will require database implementation to store persistent data.

## TODO:

- [ ] Base Game
  - [ ] Register Duel Request
    - Parse and store challenger and challenged
  - [ ] Post challenge notification
    - Let people know a challenge has been issued (maybe with image or ascii art?)
  - [ ] Register Duel Accept
  - [ ] Post duel notification
    - Let people know a duel is about to start(maybe with image or ascii art?)
    - Give countdown
  - [ ] Generate math problems
    - Define difficulty levels
    - Create generate function
  - [ ] Post problems
  - [ ] Register answers
    - Accept only duelists
    - Store and track hits
    - Report results (@ user1 hit @ user 2 for x damage ...)
  - [ ] Register game over
  - [ ] Report duel results

- [ ] Advanced Features (Requires DB)
  - [ ] Avatars
  - [ ] Experience System
  - [ ] Equipment System
  - [ ] Abilities
